FROM golang:1.25.11-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o server ./cmd/server/.

FROM scratch
COPY --from=builder /app/server /server
USER 65532:6553
ENTRYPOINT [ "/server" ]
